server:
  port: 8089
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: service-feign
  mvc:
    static-path-pattern=/static/**:

    thymeleaf:
      encoding: UTF-8
      servlet:
        content-type: text/html